spring:
  application:
    name: transaksi

  profiles:
    active: local   # default kalau jalan dari IDE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Settingan database di Docker Compose
    url: jdbc:mysql://mysql-db:3306/penjualan?useSSL=false&serverTimezone=Asia/Jakarta
    username: myuser
    password: mypassword

  # KONFIGURASI RESOURCE SERVER (Validasi Token dari Google)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true