name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ] # Jalan setiap kali ada push ke main/master
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodingan kamu
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Siapkan Java 21 (Sesuai pom.xml kamu)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Test & Build file .jar pakai Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # 4. Login ke Docker Hub (Pakai Secret yang tadi dibuat)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build Docker Image & Push ke Docker Hub
    # GANTI 'username-dockerhub-kamu' di bawah ini dengan username aslimu!
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Format: username/nama-image:tag
        tags: ${{ secrets.DOCKER_USERNAME }}/transaksi-app:latest