name: CI/CD Pipeline (Build, Security, Docker Push)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- 1. SECURITY STEP (DEVSKIM) ---
      # Kita gunakan pengaturan default saja agar tidak error
      - name: Run DevSkim Static Analysis
        uses: microsoft/devskim-action@v1
          
      # --- 2. PERMISSION & BUILD STEP (MAVEN) ---
      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build with Maven (Skip Tests)
        run: ./mvnw clean package -DskipTests
        
      # --- 3. DOCKER LOGIN & PUSH STEP ---

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Image Tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Pastikan 'nama-user-docker' di bawah ini sudah sesuai atau pakai secrets
          images: ${{ secrets.DOCKER_USERNAME }}/transaksi-app 
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable=true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}